title: "Insane software adventures"
description: residentsummer's blog
meta_description:

# Site live URL
url: "https://residentsummer.github.io"
baseurl:
# No categories, no confilicts with static pages
permalink: /posts/:year/:month/:day/:slug/
# Oh, separators doesn't work through the includes
excerpt_separator: '{% include cut.html %}'

# Harmony theme configuration.
harmony:
  basetheme: theme-base-01
  # Theme author details
  author:
    name: Gayan Virajith
    email: gayanvirajith@gmail.com
    url: http://gayanvirajith.github.io

  # Google Analytics key, leave blank to ignore
  # google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social:
    github: residentsummer
    linkedin: shkalev
    feed: /feed.xml
    twitter:
    facebook:
    gplus:
    dribble:
    pinterest:

  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  enable_coderay: false
sass:
  sass_dir: assets/css/_sass
  style: :compressed
gems:
  - jekyll-redirect-from

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - theme-licence.md
  - Gemfile.lock

